import Head from 'next/head'
import styles from '../styles/Home.module.css'


const PWT = (props: any) => {
  return (
    <>
      <Head>
        <title>PWT MF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <pre>PWT MicroFront</pre>
        <pre>{JSON.stringify(props, null, 2)}</pre>
      </main>
    </>
  )
}

PWT.getInitialProps = async () => {
  const swapi = await fetch('https://jsonplaceholder.typicode.com/todos/1').then(res => res.json());
  console.log(swapi);
  console.log('swapi');
  return swapi;
};

export default PWT